require 'ostruct'
require 'rubocop'
require 'rugged'

require 'codegrade/commit'
require 'codegrade/formatter'
require 'codegrade/offense'
require 'codegrade/grader/commit_message'
require 'codegrade/grader/grader'
require 'codegrade/grader/rubocop'
